
package ventanas;

import Clases.Baraja;
import MetodosOrdenamiento.Burbuja;
import MetodosOrdenamiento.InserccionDirecta;
import MetodosOrdenamiento.Seleccion;
import MetodosOrdenamiento.Shell;
import java.util.ArrayList;
import javax.swing.JLabel;
import moverjlabel.FrameLabel;
import moverjlabel.Worker;


public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Baraja baraja = new Baraja();
    public ArrayList<JLabel> al = new ArrayList<>();

    public Menu() {

        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Ventana Cartas Palo de Corazones ♥");

        baraja.iniciarBaraja();
        baraja.showCard(label1, baraja.sacar(1));
        baraja.showCard(label2, baraja.sacar(2));
        baraja.showCard(label4, baraja.sacar(4));
        baraja.showCard(label3, baraja.sacar(3));
        baraja.showCard(label5, baraja.sacar(5));
        baraja.showCard(label8, baraja.sacar(8));
        baraja.showCard(label6, baraja.sacar(6));
        baraja.showCard(label7, baraja.sacar(7));
        baraja.showCard(label9, baraja.sacar(9));
        baraja.showCard(label13, baraja.sacar(13));
        baraja.showCard(label10, baraja.sacar(10));
        baraja.showCard(label11, baraja.sacar(11));
        baraja.showCard(label12, baraja.sacar(12));
        al.add(label1);
        al.add(label2);
        al.add(label3);
        al.add(label4);
        al.add(label5);
        al.add(label6);
        al.add(label7);
        al.add(label8);
        al.add(label9);
        al.add(label10);
        al.add(label11);
        al.add(label12);
        al.add(label13);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label4 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        label13 = new javax.swing.JLabel();
        label10 = new javax.swing.JLabel();
        label11 = new javax.swing.JLabel();
        label12 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label4.setName(""); // NOI18N
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 43, 65, 100));
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 43, 65, 100));
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 43, 65, 100));

        label3.setName(""); // NOI18N
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 43, 65, 100));
        jPanel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 149, 65, 100));

        label8.setName(""); // NOI18N
        jPanel1.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 149, 65, 100));
        jPanel1.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 149, 65, 100));

        label7.setName(""); // NOI18N
        jPanel1.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 149, 65, 100));
        jPanel1.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 261, 65, 100));

        label13.setName(""); // NOI18N
        jPanel1.add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 149, 65, 100));
        jPanel1.add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 261, 65, 100));

        label11.setName(""); // NOI18N
        jPanel1.add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 261, 65, 100));

        label12.setName(""); // NOI18N
        jPanel1.add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 261, 65, 100));

        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        jButton2.setText("Metodo Inserccion");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton1.setText("Metodo Burbuja");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton3.setText("Metodo Shell");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setText("Metodo Seleccion");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton5.setText("Desordenar");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jPanel1.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 149, 147, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Free-Dark-Blue-Wallpaper-High-Quality.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -7, 710, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //METODO DE INSERCCION
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        FrameLabel fa;

        fa = new FrameLabel(al, baraja.getListavalores());//frame al que enviamos una lista de labels y una lista con los valores de las cartas
        fa.setTitle("Metodo Burbuja Simple");
        fa.setVisible(true);//ponemos el frame como visible
        fa.setLocationRelativeTo(null);//centamos el frame
        this.setVisible(false);//ocultamos este frame

        //creamos el arreglo
        int[] arreglo = new int[13];//creamos un arreglo que pasaremos al metodo
        for (int i = 0; i < 13; i++) {
            arreglo[i] = baraja.getListavalores().get(i);//asignamos los valores que tiene la baraja , y que fueron desordenados
        }
        InserccionDirecta b = new InserccionDirecta(arreglo);//instanciamos la clase burbuja
        b.ordenar();
        Worker h = new Worker(fa, b.p1, b.p2);

        h.execute();
        fa.jTextField1.setText(String.valueOf(b.getComparaciones()));
        fa.jTextField2.setText(String.valueOf(b.getIntercambios()));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        baraja.desordenar();

        for (int i = 0; i < 13; i++) {
            int valor = baraja.listavalores.get(i);
            baraja.showCard(al.get(i), baraja.sacar(valor));
        }


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
        FrameLabel fa;

        fa = new FrameLabel(al, baraja.getListavalores());//frame al que enviamos una lista de labels y una lista con los valores de las cartas
        fa.setTitle("Metodo Burbuja Simple");
        fa.setVisible(true);//ponemos el frame como visible
        fa.setLocationRelativeTo(null);//centamos el frame
        this.setVisible(false);//ocultamos este frame

        //creamos el arreglo
        int[] arreglo = new int[13];//creamos un arreglo que pasaremos al metodo
        for (int i = 0; i < 13; i++) {
            arreglo[i] = baraja.getListavalores().get(i);//asignamos los valores que tiene la baraja , y que fueron desordenados
        }
        Burbuja b = new Burbuja(arreglo);//instanciamos la clase burbuja
        b.ordenar();
        Worker h = new Worker(fa, b.p1, b.p2);

        h.execute();
        fa.jTextField1.setText(String.valueOf(b.getComparaciones()));
        fa.jTextField2.setText(String.valueOf(b.getIntercambios()));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        FrameLabel fa;

        fa = new FrameLabel(al, baraja.getListavalores());//frame al que enviamos una lista de labels y una lista con los valores de las cartas
        fa.setTitle("Metodo Seleccion Simple");
        fa.setVisible(true);//ponemos el frame como visible
        fa.setLocationRelativeTo(null);//centamos el frame
        this.setVisible(false);//ocultamos este frame

        //creamos el arreglo
        int[] arreglo = new int[13];//creamos un arreglo que pasaremos al metodo
        for (int i = 0; i < 13; i++) {
            arreglo[i] = baraja.getListavalores().get(i);//asignamos los valores que tiene la baraja , y que fueron desordenados
        }
        Seleccion s = new Seleccion(arreglo);//instanciamos la clase burbuja
        s.ordenar();
        Worker h = new Worker(fa, s.p1, s.p2);

        h.execute();
        fa.jTextField1.setText(String.valueOf(s.getComparaciones()));
        fa.jTextField2.setText(String.valueOf(s.getIntercambios()));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        FrameLabel fa;

        fa = new FrameLabel(al, baraja.getListavalores());//frame al que enviamos una lista de labels y una lista con los valores de las cartas
        fa.setTitle("Metodo Shell");
        fa.setVisible(true);//ponemos el frame como visible
        fa.setLocationRelativeTo(null);//centamos el frame
        this.setVisible(false);//ocultamos este frame

        //creamos el arreglo
        int[] arreglo = new int[13];//creamos un arreglo que pasaremos al metodo
        for (int i = 0; i < 13; i++) {
            arreglo[i] = baraja.getListavalores().get(i);//asignamos los valores que tiene la baraja , y que fueron desordenados
        }
        Shell s = new Shell(arreglo);
//instanciamos la clase burbuja
        s.ordenar();
        Worker h = new Worker(fa, s.p1, s.p2);

        h.execute();
        fa.jTextField1.setText(String.valueOf(s.getComparaciones()));
        fa.jTextField2.setText(String.valueOf(s.getIntercambios()));
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    // End of variables declaration//GEN-END:variables
}
